[project]
name = "aluguelsystem"
version = "0.1.0"
description = "Sistema de gestÃ£o para aluguel de equipamentos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.2",
    "pillow>=11.2.1",
]
